### ISSUE TITLE
Support multiple windows, dragging tabs between them

### ISSUE THREAD

**Issue by solemnwarning** [solemnwarning/rehex#12]
...like Chrome and other fancy tabbed applications

**Comment by learn-more** [comment]
One solution would be to bind to the `wxEVT_AUINOTEBOOK_DRAG_MOTION` on the `notebook` control,
and when the mouse is over a window that is not in our process, start a drag & drop operation.

Downside of this would be that once the d&d operation is started, the only way to abort it is by user input, so when dragging the cursor back over 'our' window, tab-reordering suddenly stops working.
If this sounds like a reasonable consession, the implementation could be relatively simple.

Otherwise it would probably require implementing something that always starts a d&d operation on tab 'drag', 
and as part of that operation is able to re-order tabs.

**Comment by solemnwarning** [comment]
I hadn't spent too much time looking into this before, but one conclusion I had reached is that all windows would probably be in the same process - does that make the drag and drop between windows any easier?

**Comment by learn-more** [comment]
> I hadn't spent too much time looking into this before, but one conclusion I had reached is that all windows would probably be in the same process - does that make the drag and drop between windows any easier?

At least on windows, I doubt this will make a difference.
Probably the only way to properly support this, would be to completely take over the dragging of tabs from wxwidgets,
immediately start a drag/drop operation when the user drags a tab, and communicate with the window under the cursor if it is ours (or another rehex instance)

**Comment by solemnwarning** [comment]
Merged in 370031ab3dc2d22d9db8ebeb8278fe3fd5ba0e3d
