### ISSUE TITLE
Cross-platform CI builds on GitHub Actions

### ISSUE THREAD

**Issue by nightlark** [solemnwarning/rehex#120]
Would there be interest in having cross-platform (Linux, macOS, Windows) CI builds set up for this project under GitHub Actions? 

It could automatically run to check that incoming PRs build, and could be set up to include the compiled binaries as artifacts for the jobs under the Actions tab as a "nightly" (or current development branch) builds for people who want to test the latest changes.

**Comment by nightlark** [comment]
I noticed there's something set up with buildkite set up, but it looks like it's not running for PRs (or is inconsistent in when it runs?). I didn't see any buildkite config file in the repository either.

**Comment by solemnwarning** [comment]
I don't think there's much point in migrating from Buildkite to GitHub Actions at this point, unless there's something I'm missing?

The Buildkite job doesn't automatically run on PRs, since it runs on my own build machines and isn't sandboxed enough to pipe unknown code through it. I queue it to run on PRs after I review them.
