### ISSUE TITLE
Feature Request: Byte-level full-file histogram statistics

### ISSUE THREAD

**Issue by christopherball** [solemnwarning/rehex#140]
In some Hex Editors, I've seen the feature which essentially renders a histogram representing the full contents of the file, walking through each unique byte of the file.  Along the x-axis represents each unique byte, and along the y-axis, the count total for said byte.  This can be very helpful for identifying changes in a given file when file comparison approaches don't necessarily work (such as dynamically generated files).

Thoughts?

**Comment by solemnwarning** [comment]
Sounds useful. Is it done as a low-resolution overview, kind of like the preview-ish bit you get down the side of some text editors, or does it zoom in right down to byte precision?

**Comment by christopherball** [comment]
The general workflow allows for you to mouse-hover over a given column of the histogram (with perhaps a tooltip or something signaling which byte-value you're hovering over, such as "5F"), and if you click said column of the histogram, it would cycle your cursor selections through each present instance of said byte within the file (and probably visually highlight all of said instances also).

HxD is one such example hex editor that includes this type of "statistics" feature as they call it.  I saw it used in some Youtube videos and immediately wished the feature was included for this tool :).

**Comment by solemnwarning** [comment]
Note to self: When I get to this, also make it easy to generate stats for fields in a struct (i.e. have a data type and stride setting, or maybe selecting a column in the input or something...)

**Comment by solemnwarning** [comment]
Figured I'd post a screenshot/teaser of this:

![image](https://user-images.githubusercontent.com/9392044/198054144-dec19382-7db6-4a71-9349-00369d8bbd10.png)

Not finished yet, but available on the `data-histogram` branch, it will count 8/16/32/64 bit values in the file, with a given stride and count them in to a selectable number of buckets/columns (16 shown).

If a column encompasses more than one value, then clicking it descends into a new chart separating out the column's range into a new set of columns. You can keep doing this until each column is a single value.

Also planning on making it support working on selections, so you can get a chart of values from a particular byte range in the file, or a particular field of a repeated struct using the stride option (for example). Needs more thought as I want it to integrate properly with the virtual sections rather than just using file offsets like most of the existing tools.

**Comment by christopherball** [comment]
Sweet - glad to see this old feature request of mine is going to see the light of day!  Looking pretty promising so far.

**Comment by solemnwarning** [comment]
Unfortunately the preview I posted before had some usability issues, and also some technical issues when I tried improving it, so I wound up simplifying it down to only working with single-byte values for now :(

![image](https://user-images.githubusercontent.com/9392044/201546274-20b0a4ac-82d3-46e7-b40b-1d295faeefb2.png)

It can accumulate bytes from the whole file or a specific region, and you can zoom/pan the chart to see more detail, but that's about it for now.

**Comment by solemnwarning** [comment]
Merged in 758743d28b1a347890ff52abf49e3d11d7a2c5d9.
