### ISSUE TITLE
Many suggestions

### ISSUE THREAD

**Issue by peter8777555** [solemnwarning/rehex#172]
Hi Sir,

See pictures for more details and thank you for good tool.

![z1](https://user-images.githubusercontent.com/29886853/168660801-5ddce38a-ed45-4011-8e6f-a4a8eac14320.png)

![z2](https://user-images.githubusercontent.com/29886853/168660813-7cf1257b-f507-47c6-b0b2-2d5b56503a00.png)

![z3](https://user-images.githubusercontent.com/29886853/168660816-9bbc40eb-38f5-49a7-99a9-a7ec35243680.png)

![z4](https://user-images.githubusercontent.com/29886853/168660821-c14c921b-0950-403e-9a0b-4b7bfc7004b8.png)

![z5](https://user-images.githubusercontent.com/29886853/168664413-3ff35df7-c503-491c-931e-38572b44215a.png)

![z6](https://user-images.githubusercontent.com/29886853/168664416-1d3efc65-fea5-4260-ae86-f4447a01ce2c.png)

**Comment by solemnwarning** [comment]
Hi

Thank you for all the feedback, its good to know someone is using my software so much to have that much to say about it :)

See below for comments on some of the individual points:

> ![z1](https://user-images.githubusercontent.com/29886853/168660801-5ddce38a-ed45-4011-8e6f-a4a8eac14320.png)

> From cursor disassembly

The disassembly panel on the right will try to disassemble from the current cursor position - the only time it adjusts the start back or forwards is if there isn't a valid opcode starting at the current offset.

> File Offset / VA / RVA

The virtual offsets feature is relatively new in rehex, and I've only recently started getting feedback from people using it - which is why a lot of parts of the program ignore it. I'm aiming to make everything use virtual addresses when virtual addressing is selected for the file in the main view when I get around to it.

> ![z2](https://user-images.githubusercontent.com/29886853/168660813-7cf1257b-f507-47c6-b0b2-2d5b56503a00.png)

> Add option for Dec/Hex input

Decimal offsets can be entered by simply omitting the "0x" prefix, or prefixing with a leading "0" for octal.

> ![z3](https://user-images.githubusercontent.com/29886853/168660816-9bbc40eb-38f5-49a7-99a9-a7ec35243680.png)

> Add option for text decode

If you mark a range of bytes with a particular text encoding (*right click* -> *Set data type* -> *Text* -> ...), it will be decoded down the side of the main view.

> ![z6](https://user-images.githubusercontent.com/29886853/168664416-1d3efc65-fea5-4260-ae86-f4447a01ce2c.png)

> Add Code Page (936/950/...) for CJK

This should be trivial to do - I'm using iconv for the conversion so get access to all encodings it supports for free ([list here](https://gist.github.com/solemnwarning/ea77fab4be21fd7451eab156107e8526)). As you can see the list is huge and I don't know what ones are commonly/ever used... so if any in particular are commonly used for CJK (or any other languages), please list them and I'll add them all.

**Comment by peter8777555** [comment]
Hi ! Sir,

Please add code page for CJK text 

CP437

GBK 
CP936

CP950

SHIFT-JIS
CP932

UHC
CP949

![za](https://user-images.githubusercontent.com/29886853/168683414-f9b73f06-cd5d-4e9a-8460-769e29633c0d.png)

**Comment by peter8777555** [comment]
![zd](https://user-images.githubusercontent.com/29886853/168737831-e3d009b8-54bd-4510-a3bb-dcd3e49de23d.png)

![ze](https://user-images.githubusercontent.com/29886853/168737835-41a06376-56df-4a6c-a3c6-538a368e3702.png)

**Comment by solemnwarning** [comment]
FYI I've added the extra code pages and support for rendering wide characters in the text view, you can get a build of the current master branch from here: https://buildkite.com/solemnwarning/rehex/builds?branch=master

**Comment by solemnwarning** [comment]
Base options added to "Jump to offset" dialog:

![image](https://user-images.githubusercontent.com/9392044/170840960-dfb74c48-91bc-4d71-a8b0-f1bf29901c3f.png)

**Comment by solemnwarning** [comment]
I think pretty much everything in this ticket is either fixed or tracked in another ticket now, so closing.
