### ISSUE TITLE
Paste From and To

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#49]
If I want to paste the same data over and over between two points in a file, having a function to paste from and then to would be super helpful.

Alternatively this could be a 'Set bytes...' function which has it's own dialogue, you enter the hex you want to set, the offset and the end offset, and whether or not it should 'repeat until end'.

Basically I'd want to zero out an entire file or whatever or a file within a package etc., just to give you a usage idea.

**Comment by solemnwarning** [comment]
I like the "Set bytes..." dialog idea. The "repeat until end" option should probably be implicitly true, since you would otherwise just paste the hex in at the offset.

Maybe a design like the select range dialog, with an additional hex/text string input and a display of how many times it will fit into the range.

**Comment by solemnwarning** [comment]
I'm in a mood for making mock ups lately apparently:

![set](https://user-images.githubusercontent.com/9392044/93028737-b03cbe00-f60d-11ea-8b5f-57554e1504eb.png)

**Comment by learn-more** [comment]
'Fill range' or 'Fill bytes' might be a clearer title?

**Comment by solemnwarning** [comment]
Implemented in 420db27ab958a713c56deb5aca3445d1ef755550.

![fillrange](https://user-images.githubusercontent.com/9392044/94271730-f19c6a00-ff39-11ea-953f-1ed1c35a56b3.png)
