### ISSUE TITLE
[Critical Bug] signed 16bit Integer showing incorrect decimal values

### ISSUE THREAD

**Issue by zocker-160** [solemnwarning/rehex#99]
When testing with 16bit integer `E2 80` (hex: 80e2) the signed decimal is -32542 and not 32994 like shown by rehex.

It looks like the values for signed and unsigned are always the same.

![Screenshot_20201111_221006](https://user-images.githubusercontent.com/36563538/98865246-68021680-246b-11eb-9847-6118375ecce2.png)

version is the latest from master branch

EDIT: it also bugs out, when trying to put `-50` into the field manually, it directly changes to 65486

**Comment by learn-more** [comment]
Anything special you are doing?
What version are you using?

0.3.0 shows this for me:

![image](https://user-images.githubusercontent.com/610685/98867460-d8f6fd80-246e-11eb-94f4-9f6c6f9d3de1.png)

**Comment by zocker-160** [comment]
no I am not doing anything special, just open it up and type `E2 80`

I don't understand why you cannot reproduce, very strange :(

**Comment by zocker-160** [comment]
I just tested it in a VM using Ubuntu 20.04 and installed the .deb package and it has the same issue
![Screenshot_20201111_230023](https://user-images.githubusercontent.com/36563538/98869201-b31f2800-2471-11eb-8116-b3f0497d7a6e.png)

**Comment by solemnwarning** [comment]
I've seen this issue before, fix on the way.

The problem is that `decodepanel.cpp` is using the `PRId16` macro, which expands to a `%d` on Linux rather than `%hhd` for reasons best known to the GNU developers, and anything passed to a variadic function in C (e.g. `printf()`) which is smaller than an `int`, gets expanded to fit one - `be16toh()` returns an unsigned value, which gets expanded to fit the `int` and `printf()` is none the wiser (if `%hhd` was used instead, it would still be expanded within the caller, but `printf()` would truncate it correctly).

**Comment by zocker-160** [comment]
I can confirm it is working now, thank you for fixing so fast!
